config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  
  resources :charges
  resources :events

  delete "events/destroy/:id(.:format)", to: "events#destroy", as: 'destroy_event'
  get "events/subscribe/:id", to: "events#subscribe"
  get "events/closingevent/:id", to: "events#closingevent"
  post "events/pay/:id", to: "events#pay", as: "pay"
  get "events/after_subscribeandpay/:id", to: "events#after_subscribeandpay"
  get "events/after_pay/:id", to: "events#after_pay", as: 'after_pay'

  get "events/ele/:ele_id/:id", to: "events#addeletoinvitation"
  get "events/pro/:pro_id/:id", to: "events#addprotoinvitation"
  
  devise_for :pros, :controllers => { registrations: 'registrations_pro' }
  devise_for :eles, :controllers => { registrations: 'registrations_ele' }

  get "eles/index", to: "eles#index", as: "eles"
  get "eles/show/:id", to: "eles#show", as: "ele"
  get "pros/index", to: "pros#index", as: "pros"
  get "pros/show/:id", to: "pros#show", as: "pro"

end

app/models/event.rb
class Event < ApplicationRecord
    
    belongs_to :creator, class_name: "Ele", optional: true
    has_and_belongs_to_many :eleattendees, class_name: "Ele"

    belongs_to :creator, class_name: "Pro", optional: true
    belongs_to :professor, class_name: "Pro", optional: true
    has_and_belongs_to_many :proinvitatees, class_name: "Pro"


    def self.search(search)
        if search
            where(["lower(name) LIKE ? or lower(description) LIKE ? or lower(discipline) LIKE ?","%#{search.downcase}%","%#{search.downcase}%","%#{search.downcase}%"])
        else
            all
        end
    end

    def self.search2(search2)
        if search2
            where(["lower(discipline) LIKE ?", "%#{search2.downcase}%"])
        else
            all
        end
    end

    




    def self.search3(search3)
        if search3
            eleve = Ele.find_by_email(search3)
            profe = Pro.find_by_email(search3)
            if eleve == nil 
                if profe == nil
                    all
                else
                    profeid = profe.id.to_s
                    where(["cast(professor_id as text) LIKE ?", "%#{profeid}%"])
                end
            else
                if profe == nil
                    eleveid = eleve.id.to_s
                    where(["cast(asubscribe as text) LIKE ?", "%#{eleveid}%"])
                else
                    eleveid = eleve.id.to_s
                    profeid = profe.id.to_s
                    where(["cast(asubscribe as text) LIKE ? or cast(professor_id as text) LIKE ?", "%#{eleveid}%", "%#{profeid}%"])
                end
            end
        else
            all
        end
    end



    def self.search4(search4)
        if search4
            datetimenow = DateTime.now 
            if search4 == 'Les 7 prochains jours'
                where('date BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now+7.day).all
            elsif search4 == 'Les 30 prochains jours'
                where('date BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now+30.day).all
            elsif search4 == 'Tous les événements futurs'
                where('date BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now+5.year).all
            elsif search4 == 'Tous les événements passés'
                where('date BETWEEN ? AND ?', DateTime.now-5.year, DateTime.now.beginning_of_day).all
            else
                all
            end
        else
            all
        end
    end




    
    def self.search5(search5)
        if search5 == 'Les lundis'     
            where("trim(to_char(date, 'Day')) = ? ", "Monday")    
        elsif search5 == 'Les mardis'     
            where("trim(to_char(date, 'Day')) = ? ", "Tuesday") 
        elsif search5 == 'Les mercredis'     
            where("trim(to_char(date, 'Day')) = ? ", "Wednesday") 
        elsif search5 == 'Les jeudis'     
            where("trim(to_char(date, 'Day')) = ? ", "Thursday") 
        elsif search5 == 'Les vendredis'     
            where("trim(to_char(date, 'Day')) = ? ", "Friday") 
        elsif search5 == 'Les samedis'     
            where("trim(to_char(date, 'Day')) = ? ", "Saturday")
        elsif search5 == 'Les dimanches'     
            where("trim(to_char(date, 'Day')) = ? ", "Sunday") 
        else
            all
        end
    end

    



    def self.search6(search6)
        if search6 == nil
            all
        else 
            sss = search6.to_s
            where(["cast(date as text) LIKE ?", "%#{sss}%" ])
        end
    end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @events = @events.search(params[:search])
    @events = @events.search2(params[:search2])
    @events = @events.search3(params[:search3])
    @events = @events.search4(params[:search4])
    @events = @events.search5(params[:search5])
    @events = @events.search6(params[:search6])
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @allele = Ele.all
    @allpro = Pro.all
    
    if @event.naturecreateur == "eleve"
      @creator = Ele.find(@event.creator_id)
    elsif @event.naturecreateur == "professeur"
      @creator = Pro.find(@event.creator_id)
      @professor = Pro.find(@event.professor_id)
    else
    end
    if @event.professeur == "present"
      @professor = Pro.find_by_id(@event.professor_id)
    else
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.professeur = "vide"
    @event.etat = "open"
    
    if ele_signed_in?
      @event.creator_id = current_ele.id
      @event.naturecreateur = "eleve"
      @event.asubscribe << 0
      @event.apayer << 0
    elsif pro_signed_in?
      @event.creator_id = current_pro.id
      @event.naturecreateur = "professeur"
      @event.professeur = "present"
      @event.professor_id = current_pro.id
      @event.asubscribe << 0
      @event.apayer << 0
    else
    end

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def subscribe
    @event = Event.find(params[:id])
    @user = current_ele
    @pro = current_pro

    if ele_signed_in?
      @event.eleattendees << current_ele
      @event.update_attribute(:asubscribe, @event.asubscribe << current_ele.id)
    else
      
        @event.proinvitatees << current_pro
        @event.professor_id == nil
        @event.update_column(:professor_id, current_pro.id)
        @event.update_column(:professeur, "present")
      
    end
    redirect_to @event
  end


  def pay
    @user = current_ele
    @event = Event.find(params[:id])
# faire payer grace a stripe et une fois que c'est fait, envoie de l'email avec pass
    @amount = 500
        
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path


    redirect_to @event
  end

  
# devrait être nommée def after_after_subscribeandpay, à corriger, avec recherche, remplace
  def after_subscribeandpay
    @event = Event.find(params[:id])
    if ele_signed_in?
      @event.eleattendees << current_ele.id
      @event.update_attribute(:asubscribe, @event.asubscribe << current_ele.id)
      @event.update_attribute(:apayer, @event.apayer << current_ele.id)
    end
    redirect_to @event
  end

# Le .include, faut peut être le mettre dans un .each, ou peut être qu'il n'est pas nécessaire
  def after_pay
    @event = Event.find(params[:id])
    @user = current_ele
    if ele_signed_in?
      @event.asubscribe.each do |iiid|
        if current_ele.id == iiid
          @event.update_attribute(:apayer, @event.apayer << current_ele.id)
        end
      end
    else
    end
    redirect_to @event
  end

  


  def addeletoinvitation  
    @ele = Ele.find(params[:ele_id])
    @event = Event.find(params[:test])
 #   if 
 #   @event.attendees.include? @user
 #   flash[:danger] = "#{@user.name} participe déjà à l'événement !" 
 #   redirect_to @event
 #   else
    @event.eleattendees << @ele
    flash[:success] = "#{@ele.firstname} est ajouté à l'événement ! !" 
    redirect_to @event
 #   end
  end


  def addprotoinvitation  
    @pro = Pro.find(params[:pro_id])
    @event = Event.find(params[:test])
 #   if 
 #   @event.attendees.include? @user
 #   flash[:danger] = "#{@user.name} participe déjà à l'événement !" 
 #   redirect_to @event
 #   else
    @event.proinvitatees << @pro
    flash[:success] = "#{@pro.firstname} est ajouté à l'événement ! !" 
    redirect_to @event
 #   end
  end


  def closingevent
    @event = Event.find(params[:id])
    @event.update_columns(etat: "close")
    

  # il faudra qu'elle envoie un mail à tous les ele enregistrés dans @event.asubscribeX
  # "le prof a validé l'event, allez sur la page de l'event pour payer et recevoir votre pass"
    redirect_to @event
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from  the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {})
      params.require(:event).permit(:name, :discipline, :description, :date, :ville, :prix)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="backim">
</br></br></br>
<%-#                      Pour mettre à gauche:  rajouter 'gauche' apres 'container' dans class de prochaine div                 -%>
  <div class="container text-body writingbigbig">
    <h1 class="text-center"> Créer un événement </h1> </br></br>
    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %></br>


      <div class="field shadow p-4 border-top bgyellow1">
        <div class="writingbigbigbig text-center">
          <%= form.label :name %>
        </div>
        <div class="text-center text-body">
          <%= form.text_field :name, placeholder: "Cours de Slackline débutant" %>
        </div>
      </div></br></br></br>




      <div class="field bgyellow1">
        <div class="writingbigbigbig text-center border-top border-right border-left p-4">
          <%= form.label :discipline %>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="contentsize p-4 shadow">
              <p class="text-center font-weight-bold writingbig"> 1. Visualises la liste des catégories et sous-catégories </p>
              </br> 
              <p class="d-inline writingbigbig">-> DANSE :</p>
              <p class="d-inline writingbigbig">Hip-hop, Capoeira, Danse Latine, Autre</p><p class="d-inline writingbigbig">, </p> 
              </br><p class="d-inline writingbigbig">-> BIEN-ÊTRE :</p>
              <p class="d-inline writingbigbig">Workout, Pilat, Yoga, Running, Urban Fishing</p><p class="d-inline writingbigbig">, </p>  
              </br><p class="d-inline writingbigbig">-> AGILITE :</p>
              <p class="d-inline writingbigbig">Parkour, Slackline, Jonglage, Monocycle, Roue Cyr, Autre</p><p class="d-inline writingbigbig">, </p> 
              </br><p class="d-inline writingbigbig">-> GLISSE :</p>
              <p class="d-inline writingbigbig">Roller </p><p class="d-inline">(Ballade, Slalom, Quad, Vitesse, Agressif, Autre)</p><p class="d-inline writingbigbig">,</p>
                                                            </br><p class="d-inline writingbigbig">&emsp;&emsp;&emsp;&emsp;&emsp;Board </p><p class="d-inline">(Skateboard, Longboard, Trotinette, Autre)</p>
                                                            </br><p class="d-inline writingbigbig">&emsp;&emsp;&emsp;&emsp;&emsp;Vélo</p> <p class="d-inline">(Fixi, Vitesse, BMX, Autre)</p> <p class="d-inline writingbigbig">, Autre Glisse</p><p class="d-inline writingbigbig">, </p> 
              </br><p class="d-inline writingbigbig">-> TRUC-URBAIN :</p>
              <p class="d-inline writingbigbig">Foot urbain, Golf urbain, Streetball, Graff, Autre</p>
            </div> 
          </div>
            </br></br>
          <div class="col-4">
            <div class="contentsize p-4 shadow">
              <div class="text-body">
                <p class="text-center font-weight-bold writingbig"> 2. Choisis une "===CATÉGORIE===" ou une "Sous-Catégorie" <p></br>
                <div class="text-center">
                  <%= form.select :discipline,
                  [['=====DANSE=====', 'DANSE', {class: 'writingbigbigbig bgjaunetrpal'}], ['Hip-Hop', 'Hip-Hop (Danse)', {class: 'bgjaunetrpal'}], ['Capoeira', 'Capoeira (Danse)', {class: 'bgjaunetrpal'}], ['Danse Latine', 'Danse Latine (Danse)', {class: 'bgjaunetrpal'}], ['Autre Danse', 'Autre Danse', {class: 'text-primary bgjaunetrpal'}],
                  ['====BIEN ÊTRE====', 'BIEN ÊTRE', {class: 'writingbigbigbig bgviolettrpal'}], ['Workout', 'Workout (Bien Être)', {class: 'bgviolettrpal'}], ['Pilat', 'Pilat (Bien Être)', {class: ' bgviolettrpal'}], ['Yoga', 'Yoga (Bien Être)', {class: 'bgviolettrpal'}], ['Running', 'Running (Bien Être)', {class: 'bgviolettrpal'}], ['Urban Fishing','Urban Fishing (Truc Urbain)', {class: 'bgviolettrpal'}], ['Autre Bien Être', 'Autre Bien Être', {class: 'text-primary bgviolettrpal'}],
                  ['====AGILITÉ====', 'AGILITÉ', {class: 'writingbigbigbig bgverttrpal'}], ['Parkour', 'Parkour (Agilité)', {class: 'bgverttrpal'}], ['Slackline', 'Slackline (Agilité)', {class: 'bgverttrpal'}], ['Jonglage', 'Jonglage (Agilité)', {class: 'bgverttrpal'}], ['Monocycle', 'Monocycle (Agilité)', {class: 'bgverttrpal'}], ['Roue Cyr', 'Roue Cyr (Agilité)', {class: 'bgverttrpal'}], ['Autre Agilité', 'Agilité', {class: 'text-primary bgverttrpal'}],
                  ['=====GLISSE=====', 'Glisse', {class: 'writingbigbigbig bgbleutrpal'}],
                  ['--- Roller ---', 'Roller (Glisse)', {class: 'writingbigbigbig bgbleutrpal'}], ['Roller Ballade', 'Roller Ballade (Glisse)', {class: 'bgbleutrpal'}], ['Roller Slalom', 'Roller Slalom (Glisse)', {class: 'bgbleutrpal'}], ['Roller Quad (Glisse)', {class: 'bgbleutrpal'}], ['Roller Vitesse (Glisse)', {class: 'bgbleutrpal'}], ['Roller Agressif (Glisse)', {class: 'bgbleutrpal'}], ['Autre Roller', 'Roller Autre (Glisse)', {class: 'text-primary bgbleutrpal'}], 
                  ['--- Board ---', 'BOARD (Glisse)', {class: 'writingbigbigbig bgbleutrpal'}], ['Skateboard','Skateboard (Glisse)', {class: 'bgbleutrpal'}], ['Longboard','Longboard (Glisse)', {class: 'bgbleutrpal'}], ['Trotinette', 'Trotinette Board (Glisse)', {class: 'bgbleutrpal'}], ['Autre Board', 'Autre Board (Glisse)', {class: 'text-primary bgbleutrpal'}],
                  ['--- Vélo ---', 'VÉLO (Glisse)', {class: 'writingbigbigbig bgbleutrpal'}], ['Vélo Fixi', 'Vélo Fixi (Glisse)', {class: 'bgbleutrpal'}], ['Vélo Vitesse', 'Vélo Vitesse (Glisse)', {class: 'bgbleutrpal'}], ['Vélo BMX', 'Vélo BMX (Glisse)', {class: 'bgbleutrpal'}], ['Autre vélo', 'Autre vélo (Glisse)', {class: 'text-primary bgbleutrpal'}],
                  ['Autre glisse', 'Autre Glisse', {class: 'text-primary bgbleutrpal'}],
                  ['===TRUC URBAIN===', 'TRUC URBAIN', {class: 'writingbigbigbig bgrougetrpal'}],['Foot urbain', 'Foot urbain (Truc Urbain)', {class: 'bgrougetrpal'}], ['Golf urbain', 'Golf urbain (Truc Urbain)', {class: 'bgrougetrpal'}], ['Streetball', 'Streetball (Truc Urbain)', {class: 'bgrougetrpal'}], ['Graff', 'Graff (Truc Urbain)', {class: 'bgrougetrpal'}], ['Urban Fishing', 'Urban Fishing (Truc Urbain)', {class: 'bgrougetrpal'}], ['Autre Truc Urbain', 'Autre Truc Urbain', {class: 'text-primary bgrougetrpal'}]], 
                  :disabled => ["==============", '- - - - - - - - - - -'], :include_blank => true, :class => "text-danger" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div></br></br></br>   





      <div class="field shadow p-4 border-top bgyellow1">
        <div class="writingbigbigbig text-center">
          <%= form.label :description %>
        </div>
        <div class="text-center text-body">
          <%= form.text_field :description %>
        </div>
      </div></br></br></br>

      <div class="field shadow p-4 border-top bgyellow1">
        <div class="writingbigbigbig text-center">
          <%= form.label :ville %>
        </div>
        <div class="text-center text-body">
          <%= form.text_field :ville %>
        </div>
      </div></br></br></br>

      <div class="field shadow p-4 border-top bgyellow1">
        <div class="writingbigbigbig text-center">
          <%= form.label :price %>
        </div>
        <div class="text-center">
          <p> Prix min conseillé pour que levent soit attractif pour les professeurs : 3€ <p>
          <p> Prix max conseillé pour que levent soit attractif pour les élèves : 5€ <p>
        </div>
        <div class="text-center text-body">
          <%= form.text_field :price %><p>€</p>
        </div>
      </div></br></br></br>

      <div class="field shadow p-4 border-top bgyellow1">
        <div class="writingbigbigbig text-center">
          <%= form.label :date %>
        </div>
        <div class="text-center text-body">
          <%= form.datetime_select :date %>
        </div>
      </div></br></br></br>

      <p class="text-center"> Manque nature_evenement et mots_clés </p></br></br>


      <div class="actions text-center text-body">
        <div class="text-center">
          <%= form.submit :class=>'bgyellow4 majuscule bold writingbigbigbig' %>
        </div>
      </div></br>
    <% end %>

  </div>
</div>

app/views/events/destroy.html.erb
<p> L événement <%= @event.name %> a bien été supprimé </p>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/pay.html.erb
<div class="text-body">

    Votre paiement a bien été enregistré, vous allez recevoir un mail avec votre pass

    <% if @event.asubscribe.include? current_ele.id %>
        <p class="text-center">  <%= link_to "valider votre inscription", { :controller => "events", :action => "after_pay"}, class: "btn btn-success" %> </p>
    <% else %>
        <p>  <%= link_to "Valider votre inscription", { :controller => "events", :action => "after_subscribeandpay"}, class: "btn btn-success" %> </p>
    <% end %>

</div>