config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  
  resources :charges
  resources :events

  delete "events/destroy/:id(.:format)", to: "events#destroy", as: 'destroy_event'
  get "events/subscribe/:id", to: "events#subscribe"
  get "events/closingevent/:id", to: "events#closingevent"
  post "events/pay/:id", to: "events#pay", as: "pay"
  get "events/after_subscribeandpay/:id", to: "events#after_subscribeandpay"
  get "events/after_pay/:id", to: "events#after_pay", as: 'after_pay'

  get "events/ele/:ele_id/:id", to: "events#addeletoinvitation"
  get "events/pro/:pro_id/:id", to: "events#addprotoinvitation"
  
  devise_for :pros, :controllers => { registrations: 'registrations_pro' }
  devise_for :eles, :controllers => { registrations: 'registrations_ele' }

  get "eles/index", to: "eles#index", as: "eles"
  get "eles/show/:id", to: "eles#show", as: "ele"
  get "pros/index", to: "pros#index", as: "pros"
  get "pros/show/:id", to: "pros#show", as: "pro"

end

app/models/ele.rb
class Ele < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_and_belongs_to_many :eleattended_events, class_name: "Event"
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/eles_controller.rb
class ElesController < ApplicationController
    def index
        @eles = Ele.all
    end
    
    def show
        @ele = Ele.find(params[:id])
    end
end

app/views/eles/index.html.erb
<div class="container">
    <h1 class="text-body"> Les élèves </h1></br></br>
    <div class="row p-2">
    <% @eles.each do |ele|%>
        <div class="col-lg-4 mb-4">
        <div class="card h-100 shadow p-2">
            <h4 class="card-header"><%= ele.firstname %></h4>
                <div class="card-body">
                    <p class="card-text">Passions : <%= ele.passion1 %>, <%= ele.passion2 %>, <%= ele.passion3 %>, <%= ele.passion4 %> </p>
                    <p class="card-text">Ville : <%= ele.ville %> </p>
                </div>
                <div class="card-footer">
                <p> <%= link_to 'Voir son profil', ele_path(ele) %> </p>
                </div>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/eles/show.html.erb
    <div class="container d-inline-block">
        <div class="text-body text-center"> <h1> <%= @ele.firstname %> </h1> </div> </br></br></br>
            <div class="bg-white">
                <div class="row p-2">
                    <div class="container p-2 border shadow">
                        <div class="col-lg-6">
                            <h2><%= @ele.firstname %></h2>
                            <ul>
                                <li> <p><strong>Passions:</strong> <%= @ele.passion1 %>, <%= @ele.passion2 %>, <%= @ele.passion3 %>, <%= @ele.passion4 %></p> </li>
                                <li><strong>Ville : </strong></br> <%= @ele.ville %></li>
                                <li><strong>Email :</strong> <%= @ele.email %> </li>
                            </ul>
                            </p>
                        </div>
                        <div class="col-lg-6">
                            <img class="img-fluid rounded" src="http://placehold.it/700x450" alt="">
                        </div>
                    </div>
                </div>
            </div>

            </br></br></br></br></br>

            <h1 class="text-center text-body">Les événements que vous avez tous les deux suivis</h1>



            </br></br></br></br>


            <h1 class="text-center text-body">Les événements que <%=@ele.firstname%>  a créé </h1>



            <div class="row p-2">
                <% if !@ele.created_events.empty? %>
                    <% @ele.created_events.each do |event| %>
                        <div class="col-lg-4 mb-4">
                            <div class="card h-100 shadow">
                                <h4 class="card-header"><%= event.name %></h4>
                                    <div class="card-body">
                                        <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                    </div>
                                    <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                    </div>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <p> <%= @ele.firstname %> n a pour le moment créer aucun event </p>
                <% end %>
            </div>


            </br></br>


            <h1 class="text-center text-body">Les événements auxquels <%=@ele.firstname%>  a participé </h1>


            <div class="row">
                <% if !@ele.eleattended_events.empty? %>
                    <% @ele.eleattended_events.each do |event| %>
                        <div class="col-lg-4 mb-4">
                            <div class="card h-100 shadow">
                                <h4 class="card-header"><%= event.name %></h4>
                                    <div class="card-body">
                                        <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                    </div>
                                    <div class="card-footer">
                                        <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                    </div>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <p> <%= @ele.firstname %> n a pour le moment aucune activité </p>
                <% end %>
            </div>



            

            <h1 class="text-center text-body">Tous les evenement à venir qui intéressent <%=@ele.firstname%> </h1>




            <div class="row">
                <% if !@ele.eleattended_events.empty? %>
                    <% @ele.eleattended_events.each do |event| %>
                        <div class="col-lg-4 mb-4">
                            <div class="card h-100 shadow">
                                <h4 class="card-header"><%= event.name %></h4>
                                    <div class="card-body">
                                        <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                    </div>
                                    <div class="card-footer">
                                        <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                    </div>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <p> <%= @ele.firstname %> n a pour le moment aucune activité </p>
                <% end %>
            </div>

        </div>