config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  
  resources :charges
  resources :events

  delete "events/destroy/:id(.:format)", to: "events#destroy", as: 'destroy_event'
  get "events/subscribe/:id", to: "events#subscribe"
  get "events/closingevent/:id", to: "events#closingevent"
  post "events/pay/:id", to: "events#pay", as: "pay"
  get "events/after_subscribeandpay/:id", to: "events#after_subscribeandpay"
  get "events/after_pay/:id", to: "events#after_pay", as: 'after_pay'

  get "events/ele/:ele_id/:id", to: "events#addeletoinvitation"
  get "events/pro/:pro_id/:id", to: "events#addprotoinvitation"
  
  devise_for :pros, :controllers => { registrations: 'registrations_pro' }
  devise_for :eles, :controllers => { registrations: 'registrations_ele' }

  get "eles/index", to: "eles#index", as: "eles"
  get "eles/show/:id", to: "eles#show", as: "ele"
  get "pros/index", to: "pros#index", as: "pros"
  get "pros/show/:id", to: "pros#show", as: "pro"

end

app/models/pro.rb
class Pro < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :professored_events, class_name: "Event", foreign_key: :professor_id
  has_and_belongs_to_many :proinvitated_events, class_name: "Event"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pros_controller.rb
class ProsController < ApplicationController
    def index
      @pros = Pro.all
    end
  
    def show
      @pro = Pro.find(params[:id])
    end
end

app/views/pros/index.html.erb
<div class="container">
    <h1 class="text-body"> Les professeurs </h1></br></br>
    <div class="row">
    <% @pros.each do |pro|%>
        <div class="col-lg-4 mb-4">
        <div class="card h-100">
            <h4 class="card-header"><%= pro.firstname %></h4>
                <div class="card-body">
                    <p class="card-text">Passions : <%= pro.passion1 %>, <%= pro.passion2 %>, <%= pro.passion3 %>, <%= pro.passion4 %> </p>
                    <p class="card-text">Ville : <%= pro.ville %> </p>
                </div>
                <div class="card-footer">
                <p> <%= link_to 'Voir son profil', pro_path(pro) %> </p>
                </div>
        </div>
    </div>
    <% end %>
  </div>
</div>