config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  
  resources :charges
  resources :events

  delete "events/destroy/:id(.:format)", to: "events#destroy", as: 'destroy_event'
  get "events/subscribe/:id", to: "events#subscribe"
  get "events/closingevent/:id", to: "events#closingevent"
  post "events/pay/:id", to: "events#pay", as: "pay"
  get "events/after_subscribeandpay/:id", to: "events#after_subscribeandpay"
  get "events/after_pay/:id", to: "events#after_pay", as: 'after_pay'

  get "events/ele/:ele_id/:id", to: "events#addeletoinvitation"
  get "events/pro/:pro_id/:id", to: "events#addprotoinvitation"
  
  devise_for :pros, :controllers => { registrations: 'registrations_pro' }
  devise_for :eles, :controllers => { registrations: 'registrations_ele' }

  get "eles/index", to: "eles#index", as: "eles"
  get "eles/show/:id", to: "eles#show", as: "ele"
  get "pros/index", to: "pros#index", as: "pros"
  get "pros/show/:id", to: "pros#show", as: "pro"

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default bgwrist1 shadow fixed-top">
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar-left">
            <% if ele_signed_in? %>
              <p class="d-inline text-body writingbigbigbig"><span class="glyphicon glyphicon-check"></span> <%= current_ele.firstname %>, vous êtes connecté en élève</p>
              <%= link_to destroy_pro_session_path, method: :delete, :class=>"text-body bg-transparent writingbigbigbig" do %><span class="glyphicon glyphicon-log-out"></span> Se déconnecter<%end%>
            <% elsif pro_signed_in? %>
              <p class="d-inline text-body writingbigbigbig"><span class="glyphicon glyphicon-check"></span> <%= current_pro.firstname %>, vous êtes connecté en tant que professeur</p>
              <%= link_to destroy_pro_session_path, method: :delete, :class=>"text-body bg-transparent writingbigbigbig" do %><span class="glyphicon glyphicon-log-out"></span> Se déconnecter<%end%>
            <% else %>
              <p class="d-inline"><a href="/eles/sign_up" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-user"></span> Créer compte élève</a></p>
              <p class="d-inline"><a href="/pros/sign_up" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-user"></span> Créer compte professeur</a></p>
            <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-center">
            <p class="d-inline"><a href="/" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-search"></span> RECHERCHER UN EVENT</a></p>
            <% if signed_in? %>
              <p class="d-inline"><a href="/events/new" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-upload"></span> CREER UN EVENT</a></p>
            <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          
          <% if signed_in? %>
            <p class="d-inline"><a href="/eles/index" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-search"></span> Rechercher un élève</a></p>
            <p class="d-inline"><a href="/pros/index" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-search"></span> Rechercher un professeur</a></p>
          <% else %>
            <p class="d-inline"><a href="/eles/sign_in" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-log-out"></span> Se connecter en tant qu élève</a></p>
            <p class="d-inline"><a href="/pros/sign_in" class="text-body writingbigbigbig"><span class="glyphicon glyphicon-log-out"></span> Se connecter en tant que professeur</a></p>
          <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/css/modern-business.css" rel="stylesheet">



  <style> 


    .fixe71 {position: fixed; 
            top: 71px;     
            right: 0;
            left: 0;
            z-index: 1030;}

    .contentsize {box-sizing: content-box;}
    .writingsmall {font-size: 0.95rem;}
    .writingbig {font-size: 1.2rem;}
    .writingbigbig {font-size: 1.5rem;}
    .writingbigbigbig {font-size: 1.8rem;}
    .writingbigbigbiggg {font-size: 2.2rem;}
    .writingbigbigbigbig {font-size: 2.4rem;}


    .bgbleutrpal {background-color: rgb(204, 204, 255)}
    .bgbleupal {background-color: rgb(179, 179, 255)}
    .bgbleu {background-color: rgb(128, 128, 255)}

    .bgrougetrpal {background-color: rgb(255, 204, 204)}
    .bgrougepal {background-color: rgb(255, 179, 179)}
    .bgrouge {background-color: rgb(255, 128, 128)}

    .bgviolettrpal {background-color: rgb(245, 204, 255)}
    .bgvioletpal {background-color: rgb(240, 179, 255)}
    .bgviolet {background-color: rgb(229, 128, 255)}

    .bgverttrpal {background-color: rgb(204, 255, 204)}
    .bgvertpal {background-color: rgb(179, 255, 179)}
    .bgvert {background-color: rgb(128, 255, 128)}

    .bgjaunetrpal {background-color: rgb(255, 255, 204)}
    .bgjaunepal {background-color: rgb(255, 255, 179)}
    .bgjaune {background-color: rgb(255, 255, 128)}

    .bgwater1 {background-color: rgb(235, 244, 246)}
    .bgwater2 {background-color: rgb(189, 234, 238)}
    .bgwater3 {background-color: rgb(118, 180, 189)}
    .bgwater4 {background-color: rgb(88, 102, 139)}
    .bgwater5 {background-color: rgb(94, 86, 86)}

    .bgwrist1 {background-color: rgb(227, 201, 201)}
    .bgwrist2 {background-color: rgb(244, 231, 231)}
    .bgwrist3 {background-color: rgb(238, 219, 219)}
    .bgwrist4 {background-color: rgb(206, 203, 203)}
    .bgwrist5 {background-color: rgb(203, 218, 219)}

    .bgyellow1 {background-color: rgb(255, 219, 172)}
    .bgyellow2 {background-color: rgb(241, 194, 125)}
    .bgyellow3 {background-color: rgb(224, 172, 105)}
    .bgyellow4 {background-color: rgb(198, 134, 66)}
    .bgyellow5 {background-color: rgb(141, 85, 36)}

    .backim1 {
      background-image: url(https://zupimages.net/up/18/30/nw6i.png);
      background-repeat-x: no-repeat;
      background-size: 100% ;
      background-position: fixed-top ;
    }

    .backim2 {
      background-image: url(https://zupimages.net/up/18/30/faa3.jpg);
      background-repeat-x: no-repeat;
      background-size: 100% ;
      background-position: fixed-top ;
    }
    
    .fullsizedimage {
      image-size: 100% ;
    }

    .majuscule {
      text-transform: uppercase;
    }

    .container.gauche {
      position: absolute;
      left: 70px;
      bg-transparent;
    }

    .avecperspective {
      perspective: 800px;
    }

    .stickied {
      position: sticky ;
      top: 100px ;
    }

    .colonne1sur3 {
      grid-column: 1/3;
    }
    

  </style>

  </head>

  <body class="backim2">


    <%= render "layouts/header" %>
    </br>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="application.js"></script>

    <%-#   ========================= Adaptive background  =========================    -%>
    <script type="text/javascript" src='/lib/jquery.js'></script>
    <script type="text/javascript" src='/src/jquery.adaptive-backgrounds.js'>
    <script type="text/javascript">
      $(document).ready(function(){
      $.adaptiveBackground.run()
      });
    </script>
  
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>